### ISSUE TITLE
Stray debug statement left in the code

### ISSUE THREAD

**Issue by kaushalmodi** [jixiuf/ctags-update#2]
Hello, 

Can you please delete the 

```el
(message "%dsss"(prefix-numeric-value current-prefix-arg))
```

on https://github.com/jixiuf/ctags-update/blob/f60ba3897aca83b7b0a021070de940654961f52a/ctags-update.el#L220

I was caught by surprise when all of a sudden I started seeing "1sss" in my \*Messages\* buffer. 

---

Also when you do this next time, please put a debug message like 

```el
(message "ctags-update-dbg: %dsss"(prefix-numeric-value current-prefix-arg))
```

so that a user can know where a debug message is coming from.

**Comment by jixiuf** [comment]
updated. thanks .
